swagger: '2.0'
info:
  title: addition
  description: ''
  version: '1.0'
host: elastic.snaplogic.com:443
basePath: /api/1/rest/slsched/feed/snaplogictrial/projects/addition
schemes:
- https
paths:
  /addTwoNumber task:
    post:
      consumes:
      - application/json
      parameters:
      - in: query
        name: a
        type: string
        description: ''
        required: false
      - in: query
        name: b
        type: string
        description: ''
        required: false
      produces:
      - application/json
      responses:
        '200':
          description: OK
          schema:
            items:
              properties:
                result:
                  type: number
            type: array
securityDefinitions:
  basicAuth:
    type: basic
security:
- basicAuth: []
