swagger: '2.0'
info:
  title: AjayChawda
  description: ''
  version: '1.0'
host: elastic.snaplogic.com:443
basePath: /api/1/rest/slsched/feed/Partners/Tech Mahindra/AjayChawda
schemes:
- https
paths:
  /additionTask:
    post:
      consumes:
      - application/json
      parameters:
      - in: query
        name: a
        type: string
        description: ''
        required: false
      - in: query
        name: b
        type: string
        description: ''
        required: false
        default: '10'
      - in: body
        name: input0
        description: ''
        schema:
          items:
            type: object
          type: array
      produces:
      - application/json
      responses:
        '200':
          description: OK
securityDefinitions:
  basicAuth:
    type: basic
security:
- basicAuth: []
