basePath: /demo1/Partners/Tech Mahindra/AjayChawda
host: prod-partners-apim.snaplogic.io
info:
  description: ''
  title: demo1
  version: '1.0'
paths:
  /additionTask:
    post:
      consumes:
      - application/json
      parameters:
      - description: ''
        in: query
        name: a
        required: false
        type: string
      - default: '10'
        description: ''
        in: query
        name: b
        required: false
        type: string
      - description: ''
        in: body
        name: input0
        schema:
          items:
            type: object
          type: array
      produces:
      - application/json
      responses:
        '200':
          description: OK
schemes:
- https
security:
- basicAuth: []
securityDefinitions:
  basicAuth:
    type: basic
swagger: '2.0'
